<?xml version='1.0' encoding='UTF-8'?>
<defects4j>
    <project projectid="Time">
        <bug bugid="Time-18">
            <tests>
                <testfile path="org/joda/time/chrono/TestGJChronology">
                    <exception>org.joda.time.IllegalFieldValueException:Value 29 for
                        dayOfMonth must be in the range [1,28]
                    </exception>
                </testfile>
                <spectra>
                    <number_tests>2546</number_tests>
                    <failed>1</failed>
                    <passed>2545</passed>
                    <nodes>13252</nodes>
                </spectra>
            </tests>
            <fixlocations>
                <file path="org/joda/time/chrono/GJChronology.java">
                    <insert numberlines="1,11">364,367</insert>
                    <bugtypes>
                        <id id="1.3" lines="363,366">
                            <description>Missing exception handling.</description>
                        </id>
                    </bugtypes>
                </file>
            </fixlocations>
            <numberfixedlines>2</numberfixedlines>
        </bug>
    </project>
</defects4j>
